server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    max-connections: 10000
    threads:
      max: 200
    accept-count: 100
    connection-timeout: 5000

spring:
  application:
    name: annotation
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    async:
      request-timeout: 60000
  task:
    execution:
      pool:
        core-size: 10
        max-size: 50
        queue-capacity: 100
        keep-alive: 60s

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    com.monitor.annotation: DEBUG
    org.springframework.web: INFO


management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always


